HuntkingdomBundle\Entity\Commande:
    type: entity
    table: commande
    id:
        idcmd:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
        quantite:
            type: integer
            nullable: false
            options:
                unsigned: false
        prixTotal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: prix_total
        etat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
