HuntkingdomBundle\Entity\Panier:
    type: entity
    table: panier
    id:
        idp:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
        nomp:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nomP
        quantite:
            type: integer
            nullable: false
            options:
                unsigned: false
        prix:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
