HuntkingdomBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        quantite:
            type: integer
            nullable: false
            options:
                unsigned: false
        prix:
            type: integer
            nullable: false
            options:
                unsigned: false
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prixPromo:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: prix_promo
    lifecycleCallbacks: {  }
