HuntkingdomBundle\Entity\Promotion:
    type: entity
    table: promotion
    indexes:
        id_produit:
            columns:
                - id_produit
    id:
        idPromotion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_promotion
            generator:
                strategy: IDENTITY
    fields:
        idProduit:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_produit
        taux:
            type: float
            nullable: false
            precision: 10
            scale: 0
        dateDebut:
            type: date
            nullable: false
            column: date_debut
        dateFin:
            type: date
            nullable: false
            column: date_fin
    lifecycleCallbacks: {  }
