HuntkingdomBundle\Entity\Publicite:
    type: entity
    table: publicite
    id:
        idPublicite:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_publicite
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dateDebut:
            type: date
            nullable: false
            column: date_debut
        dateFin:
            type: date
            nullable: false
            column: date_fin
        nomProprietaire:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: nom_proprietaire
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
